{% set name = "libertem-blobfinder" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libertem-blobfinder-{{ version }}.tar.gz
  sha256: 340034189d289a250f5476f2ec16361d5ebbb0628b416e211505fac26974804a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - numba >=0.49
    - pyfftw
    - scikit-image
    - hdbscan

test:
  imports:
    - libertem_blobfinder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://libertem.github.io/LiberTEM-blobfinder
  summary: LiberTEM correlation and refinement library
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    LiberTEM-blobfinder is a package for correlation-based
    peak finding and strain mapping. It is part of the
    LiberTEM project.

extra:
  recipe-maintainers:
    - sk1p
    - uellue
    - matbryan52
