{% set name = "libertem-blobfinder" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 78c8fd83bb212d6f4bd3db74788a48c51aafa33603e5db6e3a4c2b549bafe6e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=3.9
    - numpy
    - numba >=0.49
    - scikit-image
    - hdbscan
    - sparseconverter
    - scipy
    - sparse

test:
  imports:
    - libertem_blobfinder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://libertem.github.io/LiberTEM-blobfinder
  summary: LiberTEM correlation and refinement library
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    LiberTEM-blobfinder is a package for correlation-based
    peak finding and strain mapping. It is part of the
    LiberTEM project.

extra:
  recipe-maintainers:
    - sk1p
    - uellue
    - matbryan52
